control/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from control.views import (
    home,
    volume_converter,
    length_converter,
    time_converter,
    currency_converter,
    temperature_converter,
    weight_converter,
    speed_converter,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r"^$", home, name="home"),
    url(r"^volume_converter/$", volume_converter, name="volume_converter"),
    url(r"^length_converter/$", length_converter, name="length_converter"),
    url(r"^time_converter/$", time_converter, name="time_converter"),
    url(r"^currency_converter/$", currency_converter, name="currency_converter"),
    url(r"^temperature_converter/$", temperature_converter, name="temperature_converter"),
    url(r"^weight_converter/$", weight_converter, name="weight_converter"),
    url(r"^speed_converter/$", speed_converter, name="speed_converter"),
]

control/models.py
from django.db import models


class Currency(models.Model):
    code = models.CharField(max_length=3)
    name = models.CharField(max_length=30)

    class Meta:
        ordering = ['name']
        verbose_name = 'currency'
        verbose_name_plural = 'currencies'

control/forms.py
from django import forms

from control.models import Currency

LENGTH_CHOICES = [
    ('', 'Select..'),
    ("metre", "Metre"),
    ("kilometre", "Kilometre"),
    ("centimetre", "Centimetre"),
    ("millimetre", "Millimetre"),
    ("micrometre", "Micrometre"),
    ("nanometre", "Nanometre"),
    ("mile", "Mile"),
    ("yard", "Yard"),
    ("inch", "Inch"),
    ("foot", "Foot"),
]


class LengthConverter(forms.Form):
    unit = forms.ChoiceField(label='Unit', choices=LENGTH_CHOICES)
    unit_to = forms.ChoiceField(label='Unit to', choices=LENGTH_CHOICES)
    unit_value = forms.FloatField(initial=0)


VOLUME_CHOICES = [
    ('', 'Select..'),
    ("gallon", "Gallon"),
    ("quart", "Quart"),
    ("ounce", "Ounce"),
    ("litre", "Litre"),
    ("cup", "Cup"),
    ("tablespoon", "Tablespoon"),
    ("teaspoon", "Teaspoon"),
    ("pint", "Pint"),
    ("cubic_inch", "Cubic inch"),
    ("cubic_feet", "Cubic Feet"),
    ("cubic_yard", "Cubic yard"),
    ("milliliter", "Milliliter"),
    ("cubic_centimetre", "Cubic centimetre"),
    ("cubic_metre", "Cubic metre")
]


class VolumeConverter(forms.Form):
    unit = forms.ChoiceField(label='Unit', choices=VOLUME_CHOICES)
    unit_to = forms.ChoiceField(label='Unit to', choices=VOLUME_CHOICES)
    unit_value = forms.FloatField(initial=0)


TIME_CHOICES = [
    ('', 'Select..'),
    ('nanosecond', 'Nanosecond'),
    ('microsecond', 'Microsecond'),
    ('millisecond', 'Millisecond'),
    ('second', 'Second'),
    ('minute', 'Minute'),
    ('hour', 'Hour'),
    ('day', 'Day'),
    ('week', 'Week'),
    ('month', 'Month'),
    ('year', 'Year'),
    ('decade', 'Decade'),
    ('century', 'Century')
]


class TimeConverter(forms.Form):
    unit = forms.ChoiceField(label='Unit', choices=TIME_CHOICES)
    unit_to = forms.ChoiceField(label='Unit to', choices=TIME_CHOICES)
    unit_value = forms.FloatField(initial=0)


class CurrencyConverter(forms.Form):
    currencies = Currency.objects.all()
    currency_choices = [('', 'Select..')] + [(currency.code, currency.name) for currency in currencies]

    unit = forms.ChoiceField(label='Unit', choices=currency_choices)
    unit_to = forms.ChoiceField(label='Unit to', choices=currency_choices)
    unit_value = forms.FloatField(initial=0)


TEMPERATURE_CHOICES = [
    ('', 'Select..'),
    ('celsius', 'Celsius'),
    ('kelvin', 'Kelvin'),
    ('fahrenheit', 'Fahrenheit')
]


class TemperatureConverter(forms.Form):
    unit = forms.ChoiceField(label='Unit', choices=TEMPERATURE_CHOICES)
    unit_to = forms.ChoiceField(label='Unit to', choices=TEMPERATURE_CHOICES)
    unit_value = forms.FloatField(initial=0)


WEIGHT_CHOICES = [
    ('', 'Select..'),
    ('tonne', 'Tonne'),
    ('kg', 'Kilograms'),
    ('g', 'Grams'),
    ('mg', 'Milligram'),
    ('micro_gram', 'Micro gram'),
    ('imperial_ton', 'Imperial ton'),
    ('us_ton', 'US ton'),
    ('stone', 'Stone'),
    ('pound', 'Pound'),
    ('ounce', 'Ounce'),
]


class WeightConverter(forms.Form):
    unit = forms.ChoiceField(label='Unit', choices=WEIGHT_CHOICES)
    unit_to = forms.ChoiceField(label='Unit to', choices=WEIGHT_CHOICES)
    unit_value = forms.FloatField(initial=0)


SPEED_CHOICES = [
    ('', 'Select..'),
    ('mile_per_hour', 'Mile per hour'),
    ('foot_per_second', 'Foot per second'),
    ('metre_per_second', 'Metre per second'),
    ('kilometre_per_hour', 'Kilometre per hour'),
    ('knot', 'Knot'),
]


class SpeedConverter(forms.Form):
    unit = forms.ChoiceField(label='Unit', choices=SPEED_CHOICES)
    unit_to = forms.ChoiceField(label='Unit to', choices=SPEED_CHOICES)
    unit_value = forms.FloatField(initial=0)

control/views.py
from django.http import HttpResponse
from django.template import loader
import requests

from control.forms import (
    LengthConverter,
    VolumeConverter,
    TimeConverter,
    CurrencyConverter,
    TemperatureConverter,
    WeightConverter,
    SpeedConverter)


def home(request):
    context = {}

    template = loader.get_template('control/home.html')
    return HttpResponse(template.render(request=request, context=context))


METRE_VALUES = {
    'kilometre': 1000.0,
    'metre': 1.0,
    'centimetre': 0.01,
    'millimetre': 0.001,
    'micrometre': 10 ** -6.0,
    'nanometre': 10 ** -9.0,
    'mile': 1609.34,
    'yard': 0.9144,
    'foot': 0.3048,
    'inch': 0.0254,
}


def length_converter(request):
    result = 0

    if request.method == 'POST':
        filled_form = LengthConverter(request.POST)

        if filled_form.is_valid():
            form = filled_form
            unit = form.cleaned_data['unit']
            unit_to = form.cleaned_data['unit_to']
            unit_value = form.cleaned_data['unit_value']

            calculations = unit_value * METRE_VALUES[unit] / METRE_VALUES[unit_to]
            result = '{} {}s'.format(calculations, unit_to)

    else:
        form = LengthConverter()

    context = {'form': form, 'result': result}

    template = loader.get_template('control/generic_converter.html')
    return HttpResponse(template.render(request=request, context=context))


VOLUME_VALUES = {
    'gallon': 0.264172,
    'quart': 1.056688,
    'pint': 2.113376,
    'ounce': 33.814023,
    'litre': 1,
    'cup': 4.226753,
    'tablespoon': 67.628045,
    'teaspoon': 202.884136,
    'cubic_inch': 61.023744,
    'cubic_feet': 0.035315,
    'cubic_yard': 0.001308,
    'milliliter': 1000,
    'cubic_centimetre': 1000,
    'cubic_metre': 0.001,
}


def volume_converter(request):
    result = 0

    if request.method == 'POST':
        filled_form = VolumeConverter(request.POST)

        if filled_form.is_valid():
            form = filled_form
            unit = form.cleaned_data['unit']
            unit_to = form.cleaned_data['unit_to']
            unit_value = form.cleaned_data['unit_value']

            calculations = unit_value * VOLUME_VALUES[unit_to] / VOLUME_VALUES[unit]
            result = '{} {}s'.format(calculations, unit_to)

    else:
        form = VolumeConverter()

    context = {'form': form, 'result': result}

    template = loader.get_template('control/generic_converter.html')
    return HttpResponse(template.render(request=request, context=context))


TIME_VALUES = {
    'nanosecond': 10 ** -9,
    'microsecond': 1 ** -6,
    'millisecond': 0.001,
    'second': 1,
    'minute': 60,
    'hour': 3600,
    'day': 86400,
    'week': 604800,
    'month': 2628000,
    'year': 31556952,
    'decade': 315569520,
    'century': 3155695200,
}


def time_converter(request):
    result = 0

    if request.method == 'POST':
        filled_form = TimeConverter(request.POST)

        if filled_form.is_valid():
            form = filled_form
            unit = form.cleaned_data['unit']
            unit_to = form.cleaned_data['unit_to']
            unit_value = form.cleaned_data['unit_value']

            calculations = unit_value * TIME_VALUES[unit] / TIME_VALUES[unit_to]
            result = '{} {}s'.format(calculations, unit_to)

    else:
        form = TimeConverter()

    context = {'form': form, 'result': result}

    template = loader.get_template('control/generic_converter.html')
    return HttpResponse(template.render(request=request, context=context))


def currency_converter(request):
    result = 0

    if request.method == 'POST':
        filled_form = CurrencyConverter(request.POST)

        if filled_form.is_valid():
            form = filled_form
            unit = form.cleaned_data['unit'].upper()
            unit_to = form.cleaned_data['unit_to'].upper()
            unit_value = form.cleaned_data['unit_value']

            url = 'https://api.exchangeratesapi.io/latest?base=' + unit
            currency_values = requests.get(url).json()

            try:
                currency_value = currency_values['rates'][unit_to]

            except KeyError:
                currency_value = 1

            finally:
                calculations = unit_value * currency_value
                result = '{} {}'.format(calculations, unit_to)
    else:
        form = CurrencyConverter()

    context = {'form': form, 'result': result}

    template = loader.get_template('control/generic_converter.html')
    return HttpResponse(template.render(request=request, context=context))


def temperature_converter(request):
    result = 0

    if request.method == 'POST':
        filled_form = TemperatureConverter(request.POST)

        if filled_form.is_valid():
            form = filled_form
            unit = form.cleaned_data['unit']
            unit_to = form.cleaned_data['unit_to']
            unit_value = form.cleaned_data['unit_value']

            calculations = unit_value

            if unit == 'celsius':
                if unit_to == 'fahrenheit':
                    calculations = (1.8 * unit_value) + 32

                elif unit_to == 'kelvin':
                    calculations = unit_value + 273.15

            elif unit == 'fahrenheit':
                if unit_to == 'celsius':
                    calculations = (unit_value - 32) * 5 / 9

                elif unit_to == 'kelvin':
                    calculations = (unit_value + 459.67) * 5 / 9

            elif unit == 'kelvin':
                if unit_to == 'celsius':
                    calculations = unit_value - 273.15

                elif unit_to == 'fahrenheit':
                    calculations = (unit_value * 9 / 5) - 459.67

            result = '{} {}'.format(calculations, unit_to)

    else:
        form = TemperatureConverter()

    context = {'form': form, 'result': result}

    template = loader.get_template('control/generic_converter.html')
    return HttpResponse(template.render(request=request, context=context))


WEIGHT_VALUES = {
    'tonne': 10 ** 6,
    'kg': 1000,
    'g': 1,
    'mg': 0.001,
    'micro_gram': 10 ** -6,
    'imperial_ton': 1016046.91,
    'us_ton': 907184.74,
    'stone': 6350.29,
    'pound': 453.592,
    'ounce': 28.349500000294
}


def weight_converter(request):
    result = 0

    if request.method == 'POST':
        filled_form = WeightConverter(request.POST)

        if filled_form.is_valid():
            form = filled_form
            unit = form.cleaned_data['unit']
            unit_to = form.cleaned_data['unit_to']
            unit_value = form.cleaned_data['unit_value']

            calculations = unit_value * WEIGHT_VALUES[unit] / WEIGHT_VALUES[unit_to]
            result = '{} {}'.format(calculations, unit_to)

    else:
        form = WeightConverter()

    context = {'form': form, 'result': result}

    template = loader.get_template('control/generic_converter.html')
    return HttpResponse(template.render(request=request, context=context))


SPEED_VALUES = {
    'mile_per_hour': 1,
    'foot_per_second': 1.46667,
    'metre_per_second': 0.44704,
    'kilometre_per_hour': 1.60934,
    'knot': 0.868976,
}


def speed_converter(request):
    result = 0

    if request.method == 'POST':
        filled_form = SpeedConverter(request.POST)

        if filled_form.is_valid():
            form = filled_form
            unit = form.cleaned_data['unit']
            unit_to = form.cleaned_data['unit_to']
            unit_value = form.cleaned_data['unit_value']

            calculations = unit_value * SPEED_VALUES[unit_to] / SPEED_VALUES[unit]
            result = '{} {}'.format(calculations, unit_to)

    else:
        form = SpeedConverter()

    context = {'form': form, 'result': result}

    template = loader.get_template('control/generic_converter.html')
    return HttpResponse(template.render(request=request, context=context))

control/templates/control/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

{% block head %}
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Universal Converter</title>
{% block css %}
  <!-- Custom fonts for this template-->
  <link href={% static "vendor/fontawesome-free/css/all.min.css" %} rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href={% static "vendor/datatables/dataTables.bootstrap4.css"%} rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href={% static "css/sb-admin.css" %} rel="stylesheet">
{% endblock %}

{% block extra_css %}

{% endblock %}

</head>
{% endblock %}
<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="{% url 'home' %}">Universal Unit Converter</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href={% url "length_converter" %}>
          <i class="fas fa-fw fa-arrows-alt"></i>
          <span>Length</span>
        </a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href={% url "speed_converter" %}>
          <i class="fas fa-tachometer-alt"></i>
          <span>Speed</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url "weight_converter" %}>
          <i class="fas fa-balance-scale"></i>
          <span>Weight</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url "volume_converter" %}>
          <i class="fas fa-fw fa-flask "></i>
          <span>Volume</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url "temperature_converter" %}>
          <i class='fas fa-fw fa-thermometer-half'></i></i>
          <span>Temperature</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url "time_converter" %}>
          <i class="fas fa-fw fa-hourglass-end "></i>
          <span>Time</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url "currency_converter" %}>
          <i class="fas fa-fw fa-money-bill-alt"></i>
          <span>Currency</span>
        </a>
      </li>
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">
        {% block content %}
        <!-- Page Content -->
        <h1>Unit Converter</h1>
        <hr>
        <p>Please select any of the choices in the navigation bar on the right hand side to start converting.</p>
        {% endblock %}
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © All rights reserved to xReygen</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
  <!-- Bootstrap core JavaScript-->
  <script src={% static "vendor/jquery/jquery.min.js" %}></script>
  <script src={% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>

  <!-- Core plugin JavaScript-->
  <script src={% static "vendor/jquery-easing/jquery.easing.min.js" %}></script>

  <!-- Custom scripts for all pages-->
  <script src={% static "js/sb-admin.min.js" %}></script>

{% block extra_js %}
    <script>
    $(document).ready(function () {
    $("select").change(function () {
        var $this = $(this);
        var prevVal = $this.data("prev");
        var otherSelects = $("select").not(this);
        otherSelects.find("option[value=" + $(this).val() + "]").attr('disabled', true);
        if (prevVal) {
            otherSelects.find("option[value=" + prevVal + "]").attr('disabled', false);
        }

        $this.data("prev", $this.val());
    });

});

    </script>

     <script>
    $("#buttonswapper").click(function(e) {
    e.preventDefault();//This prevents the A tag from causing a page reload

    //Get the values
    var fromVal = $("#id_unit option:selected").val();
    var fromText = $("#id_unit option:selected").text();
    var toVal = $("#id_unit_to option:selected").val();
    var toText = $("#id_unit_to option:selected").text();

    //Set the values
    $("#id_unit option:selected").val(toVal);
    $("#id_unit option:selected").text(toText);
    $("#id_unit_to option:selected").val(fromVal);
    $("#id_unit_to option:selected").text(fromText);
});
    </script>
{% endblock %}
</body>
</html>

control/templates/control/base_converter.html
{% extends 'control/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}


    <table class="table">
  <thead>
    <tr>
      <th scope="col">Unit</th>
      <th scope="col">Value</th>
      <th scope="col">Unit To</th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{ form.unit }}</td>
      <td >{{ form.unit_value }}</td>
      <td>{{ form.unit_to }}</td>
      <td><input type="submit" value="Calculate" class="btn btn-primary"></td>
    </tr>
    </td>
    </tr>
  </tbody>
</table>
 <h2 style="text-align: center">{{ result }}</h2>
</form>

{%  endblock %}

control/templates/control/generic_converter.html
{% extends 'control/base.html' %}
{% load static %}

{% block extra_css %}
<link href={% static "css/form.css" %} rel="stylesheet">
{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}


    <table class="form-table">
  <thead>
    <tr>
      <th scope="col">Unit</th>
      <th scope="col"> </th>
      <th scope="col">Unit To</th>
      <th scope="col">Value</th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{ form.unit }}</td>
      <td><button class="btn btn-primary" id='buttonswapper'><i class="fas fa-arrows-alt-h"></i></button></td>
      <td>{{ form.unit_to }}</td>
      <td>{{ form.unit_value }}</td>
      <td><input type="submit" value="Calculate" class="btn btn-primary"></td>
    </tr>
    </td>
    </tr>
  </tbody>
</table>
 <h2 id="form-table">{{ result }}</h2>
</form>

{%  endblock %}

control/templates/control/home.html
{% extends 'control/base.html' %}